name: CI
on: [push, pull_request]
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - release-snapshot
          - snapshot

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - run: make all
    - run: make test
